CREATE TABLE `print_job` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(127) DEFAULT NULL,
  `name` VARCHAR(127) DEFAULT NULL,
  `type` VARCHAR(53) DEFAULT NULL,
  `priority` MEDIUMINT DEFAULT 65536,
  `expiresAt` TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  `deviceId` VARCHAR(127) DEFAULT NULL,
  `sourceUri` VARCHAR(255) DEFAULT NULL,
  `contentType` VARCHAR(53) DEFAULT NULL,
  `outputType` VARCHAR(53) DEFAULT NULL,
  `status` VARCHAR(53) DEFAULT NULL,
  `errorCode` INT DEFAULT NULL,
  `statusMessage` VARCHAR(255) NULL,
  `jobTicket`BLOB DEFAULT NULL,
  `callbackUri` VARCHAR(255) DEFAULT NULL,
  `createdAt` TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  `updatedAt` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE INDEX deviceId_index ON print_job (deviceId);
CREATE INDEX errorCode_index ON print_job (errorCode);

CREATE TABLE `print_job_error` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `serviceName` VARCHAR(53) DEFAULT NULL,
  `version` VARCHAR(53) DEFAULT NULL,
  `statusCode` MEDIUMINT DEFAULT NULL,
  `httpCode` SMALLINT DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  `descriptionLink` VARCHAR(255) DEFAULT NULL,
  `serviceBuild` VARCHAR(53) DEFAULT NULL,
  `details` BLOB DEFAULT NULL,
  `createdAt` TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  `updatedAt` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE TABLE `print_job_link` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `jobId` BIGINT NOT NULL,
  `clientUri` VARCHAR(255) DEFAULT NULL,
  `renderUri` VARCHAR(255) DEFAULT NULL,
  `printUri` VARCHAR(255) DEFAULT NULL,
  `outputUri` VARCHAR(255) DEFAULT NULL,
  `createdAt` TIMESTAMP DEFAULT '0000-00-00 00:00:00',
  `updatedAt` TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;

CREATE INDEX jobId_index ON print_job_link (jobId);